Repository prgrms-fe-devcourse/NFE1-1-3-KR, pull requests merged in 2024-11, with the labels that each got.

#31 Feat/#30 게시글 좋아요 api 구현
  src/api/comment.ts
  src/api/post.ts
  src/api/postLike.ts
  src/types/comment.ts
  src/types/post.ts
  src/types/supabase.ts
Labels: 📬 API

#33 Feat/#32 북마크 api 구현
  src/api/book.ts
  src/api/bookmark.ts
  src/api/index.ts
  src/types/book.ts
  src/types/supabase.ts
Labels: 📬 API

#40 Feat/#37 상세모달 API 연결
  public/default-profile.png
  public/default-profile.svg
  src/hooks/useSlider.ts
  src/pages/home/Slider.tsx
  src/pages/home/SliderItem.tsx
  src/pages/modal/BookModal.tsx
  src/pages/mypage/MyPageContent.tsx
Labels: ✨ Feature

#41 Fix/#25 모달 클로즈 애니메이션 버그 수정
  src/hooks/useSlider.ts
  src/pages/home/Slider.tsx
  src/pages/home/styles.css
  src/utils/sliderUtils.ts
Labels: 🐞 BugFix

#42 Feat/#26 커뮤니티 페이지 API 연결
  package-lock.json
  package.json
  public/Icon/check.svg
  public/Icon/setting.svg
  public/bin.svg
  public/chevron-left.svg
  public/chevron-top.svg
  public/default-bookcover.png
  public/edit-pencil.svg
  public/profile/character-0.png
  public/profile/character-1.png
  public/profile/character-2.png
  public/profile/character-3.png
  public/profile/character-4.png
  public/profile/character-5.png
  public/profile/character-6.png
  public/profile/character-7.png
  public/profile/character-8.png
  public/profile/character-9.png
  src/App.tsx
  src/components/common/Button.tsx
  src/components/common/ContentsContainer.tsx
  src/components/common/Modal/EditPostModal.tsx
  src/components/common/Modal/LoginModal.tsx
  src/components/common/Modal/ModalRenderer.tsx
  src/components/common/Modal/ModalWrapper.tsx
  src/components/common/Modal/index.ts
  src/components/common/Profile.tsx
  src/components/common/TopButton.tsx
  src/components/common/index.ts
  src/components/layout/Header.tsx
  src/constants/modalType.ts
  src/hooks/index.ts
  src/hooks/useCommunity.ts
  src/pages/community/ContentsWrapper.tsx
  src/pages/community/DetailPost.tsx
  src/pages/community/Post.tsx
  src/pages/community/SearchModal.tsx
  src/pages/community/WritePost.tsx
  src/stores/index.ts
  src/stores/useIntroStore.ts
  src/stores/usePostStore.ts
  src/stores/useSearchBookStore.ts
  src/styles/scroll.css
  src/types/post.ts
  src/utils/getRandomProfile.ts
  src/utils/index.ts
  vercel.json
  yarn.lock
Labels: ✨ Feature, 🎨 Html&css

#46 Fix/#43 슬라이더 모달 클로즈 이벤트 및 애니메이션 수정
  src/hooks/useSlider.ts
  src/pages/home/Slider.tsx
  src/pages/home/SliderItem.tsx
  src/pages/modal/BookModal.tsx
  src/utils/sliderUtils.ts
Labels: 🐞 BugFix

#50 Refact/#44 login button 수정 및 protected routes 추가
  src/App.tsx
  src/components/common/DropdownMenu.tsx
  src/components/common/HeaderProfile.tsx
  src/components/common/Modal/LoginModal.tsx
  src/components/common/Modal/ModalRenderer.tsx
  src/components/common/Modal/ModalWrapper.tsx
  src/components/common/Modal/index.ts
  src/components/common/ProtectedRoutes.tsx
  src/components/common/index.ts
  src/components/layout/Header.tsx
  src/components/layout/MenuButton.tsx
  src/hooks/index.ts
  src/hooks/useDropdown.ts
  src/hooks/useDropdownAnimation.ts
  src/stores/useAuthStore.ts
Labels: 🎨 Html&css, 🔨 Refactor

#49 Feat/#45 post 수정 레이아웃 변경 및 토스트 메시지 추가
  package.json
  src/App.tsx
  src/components/common/CustomToast.tsx
  src/components/common/Modal/EditPostModal.tsx
  src/components/common/Modal/index.ts
  src/components/common/index.ts
  src/components/layout/Header.tsx
  src/constants/modalType.ts
  src/hooks/useCommunity.ts
  src/main.tsx
  src/pages/community/CommunityPage.tsx
  src/pages/community/DetailPage.tsx
  src/pages/community/DetailPost.tsx
  src/pages/community/ListWrapper.tsx
  src/pages/community/PopularPosts.tsx
  src/pages/community/Post.tsx
  src/pages/community/WritePost.tsx
  src/pages/community/index.ts
  src/stores/usePostStore.ts
  src/styles/toast.css
  yarn.lock
Labels: ✨ Feature, 🎨 Html&css

#51 Feat/#47 북마크 API 연동
  src/App.tsx
  src/api/bookmark.ts
  src/pages/modal/BookModal.tsx
  src/pages/mypage/MyPageContent.tsx
  src/stores/index.ts
  src/stores/useBookMarkStore.ts
  src/types/book.ts
Labels: ✨ Feature

#52 Feat/#48 슬라이더 검색 기능 구현
  package.json
  src/App.tsx
  src/api/book.ts
  src/components/common/Button.tsx
  src/components/layout/MenuButton.tsx
  src/hooks/index.ts
  src/hooks/useBookList.ts
  src/pages/home/PopularBooks.tsx
  src/pages/home/SearchableBookList.tsx
  src/pages/home/SlideTemp.tsx
  src/pages/home/index.ts
  src/stores/index.ts
  src/stores/useSearchQueryStore.ts
  yarn.lock
Labels: ✨ Feature

#57 Feat/#55 메인 검색 페이지 UI 구현
  src/App.tsx
  src/components/common/ContentsContainer.tsx
  src/components/layout/Header.tsx
  src/hooks/index.ts
  src/hooks/useRandomTitle.ts
  src/pages/home/HomePage.tsx
  src/pages/home/Main.tsx
  src/pages/home/MainClouds.tsx
  src/pages/home/SearchPage.tsx
  src/pages/home/SearchableBookList.tsx
  src/pages/home/SlideTemp.tsx
  src/pages/home/Slider.tsx
  src/pages/home/SliderItem.tsx
  src/pages/home/index.ts
  src/pages/modal/BookModal.tsx
  src/utils/sliderUtils.ts
Labels: ✨ Feature, 🎨 Html&css

#60 Feat/#56 마이페이지 API 연결 및 애니메이션 개선
  public/Icon/X.svg
  src/App.tsx
  src/api/index.ts
  src/api/mypage.ts
  src/components/common/Cloud.tsx
  src/pages/modal/BookModal.tsx
  src/pages/mypage/MyPage.tsx
  src/pages/mypage/MyPageContent.tsx
  src/pages/mypage/Section.tsx
  src/types/index.ts
  src/types/section.ts
Labels: ✨ Feature

#62 Fix/#54 레이아웃 수정
  netlify.toml
  public/_redirects
  src/components/common/Background.tsx
  src/components/common/ContentsContainer.tsx
  src/components/common/Profile.tsx
  src/components/layout/Header.tsx
  src/globals.css
  src/pages/community/DetailPost.tsx
  src/pages/community/ListWrapper.tsx
  src/pages/community/Post.tsx
  src/pages/community/SearchModal.tsx
  src/pages/home/Intro.tsx
  src/pages/modal/BookModal.tsx
  src/styles/scroll.css
  tailwind.config.js
Labels: 🎨 Html&css, 🔨 Refactor, 🥰 Accessibility

#64 Fix/#59 fix header dropdown
  src/components/common/Button.tsx
  src/components/common/ContentsContainer.tsx
  src/components/common/DropdownMenu.tsx
  src/components/common/HeaderProfile.tsx
  src/components/layout/MenuButton.tsx
  src/hooks/useDropdown.ts
  src/hooks/useDropdownAnimation.ts
  src/pages/home/HomePage.tsx
  src/pages/home/SearchPage.tsx
  src/stores/useSearchQueryStore.ts
Labels: 🎨 Html&css, 🐞 BugFix, 🔨 Refactor

#69 Fix/#67 메인 페이지 모바일 레이아웃 수정
  src/components/common/Button.tsx
  src/components/layout/MenuButton.tsx
  src/pages/home/Grid.tsx
  src/pages/home/GridItem.tsx
  src/pages/home/Intro.tsx
  src/pages/home/Main.tsx
  src/pages/home/SearchPage.tsx
  src/pages/home/SearchableBookList.tsx
  src/pages/home/Slider.tsx
  src/pages/home/SliderItem.tsx
  src/pages/modal/BookModal.tsx
  src/pages/modal/Rating.tsx
  tailwind.config.js
Labels: 🎨 Html&css, 🐞 BugFix
